FUMO_GIFS = [
      "CgACAgIAAxkBAAEHeZ5g94-AeivsuMVHvSMxGf_3JiTGOAACuAsAAmPkQEroiOASMungmiAE",
      "CgACAgIAAxkBAAEHekBg95KA9lC24w8n6sAYrjQ9WlEX6gACpA4AAk49yEn7EOwECV0O7CAE",
      "CgACAgQAAxkBAAEHekpg95KULYRxr4ThTp3PBAiBBTgv5wACoAIAAjihLVNu03_gnh4vKiAE",
      "CgACAgQAAxkBAAEHemBg95LCrY4vLEAxAAEX2G50o5zIfs4AAl0CAAJyaMVSjt1xjr6KFk8gBA",
      "CgACAgQAAxkBAAEHemRg95LqLu_wqGEN9H619OSEoNDQCQACgQIAArF6pVF5-jEb0LDFziAE",
      "CgACAgQAAxkBAAEHemhg95MBU4zYQI9kikrL3fbeZyCTsQACfwIAAuHVJFEOLVY6X0knGSAE",
      "CgACAgQAAxkBAAEHemtg95MZaKHGN_xMAAGf2CVg0GLlfmUAAn0CAAI4R8VSx1-3sfZ_JjggBA",
      "CgACAgQAAxkBAAEHem5g95MuCvY-_G7IHAzcwWKUzh2pCQACmQIAAjYTfVIiYYS2_jpyCiAE",
      "CgACAgQAAxkBAAEHenFg95NG3VCeSApvDTbfDkpehywrxgACGwIAAqC7pVMo9CupI2mnxSAE",
      "CgACAgQAAxkBAAEHenVg95OUgvwzaSHX3rC6pvXaU-ohOwACqAIAAl70XVKrQdW40mnueiAE"
   ]



FUMO_STICKERS = [
     " CAACAgEAAxkBAAEHlWFg-PQuQXUuXvV_sCZ0efoDGzOpigACAgADUypEPFDutdgRH1B6IAQ",
     "CAACAgEAAxkBAAEHlWJg-PQzYkeBPo25HwP_XXQuTFKuMQACAwADUypEPCIiz7NiEMoaIAQ",
     " CAACAgEAAxkBAAEHlWNg-PQ1vTAVkeq2Df2t1ijf3VbP5AACDwADUypEPEe90ovvXiupIAQ",
     "CAACAgEAAxkBAAEHlWZg-PRAmpj4XjfQoq36CLe-m97fpQACKQADUypEPKzzVqBWxknmIAQ",
     " CAACAgEAAxkBAAEHlYhg-Paa_UMU1UqYd6Ht-D0gJIg7ZwACNAADUypEPMcOxBRUjAH6IAQ",
     "CAACAgEAAxkBAAEHlWhg-PRFu7j-2HQngZG2II_7aCZx2gACKgADUypEPAeT3YifKneTIAQ",
     "CAACAgEAAxkBAAEHlY1g-Pb8JBtp8fJTEUvXEKrG5XHxDgACXAADUypEPBRSMOhTJ24BIAQ"
   ]
